# Generated by Django 3.2.18 on 2023-03-17 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty_level', models.CharField(blank=True, choices=[('1', '1: Low'), ('2', '2: Moderate'), ('3', '3: High'), ('4', '4: Expert'), ('5', '5: Almost impossible!')], default='', max_length=1, null=True)),
                ('plant_type', models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('amaryllis', 'Amaryllis'), ('begonia', 'Begonia'), ('bulbs', 'Bulbs'), ('chillis', 'Chillis'), ('chinese_money_plant', 'Chinese money plant'), ('dragon_tree', 'Dragon Tree'), ('grape_ivy', 'Grape Ivy'), ('herbs', 'Herbs'), ('hop', 'Hop'), ('monstera_deliciosa', 'Monstera Deliciosa'), ('ornamental', 'Ornamental'), ('salads', 'Salads'), ('berries', 'Berries'), ('suculents', 'Suculents'), ('tomatoes', 'Tomatoes'), ('water_lily', 'Water Lily'), ('other', 'Other')], default='', max_length=30, null=True)),
                ('email', models.CharField(default='youremailhere@mail.com', max_length=30)),
                ('city', models.CharField(default='', max_length=30, null=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
