# Generated by Django 3.2.18 on 2023-03-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=80)),
                ('content', models.TextField(blank=True, default='')),
                ('difficulty_level', models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Moderate'), ('3', 'High'), ('4', 'Expert'), ('5', 'Almost impossible!')], default='', max_length=1, null=True)),
                ('email', models.CharField(default='youremailhere@mail.com', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('postal_code', models.CharField(max_length=15)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
