# Generated by Django 3.2.18 on 2023-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Moderate'), ('3', 'High'), ('4', 'Expert'), ('5', 'Almost impossible!')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postal_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
