# Generated by Django 3.2.18 on 2023-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('amaryllis', 'Amaryllis'), ('begonia', 'Begonia'), ('bulbs', 'Bulbs'), ('chillis', 'Chillis'), ('chinese_money_plant', 'Chinese money plant'), ('dragon_tree', 'Dragon Tree'), ('grape_ivy', 'Grape Ivy'), ('herbs', 'Herbs'), ('hop', 'Hop'), ('monstera_deliciosa', 'Monstera Deliciosa'), ('ornamental', 'Ornamental'), ('salads', 'Salads'), ('berries', 'Berries'), ('suculents', 'Suculents'), ('tomatoes', 'Tomatoes'), ('water_lily', 'Water Lily'), ('other', 'Other')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('1', '1: Low'), ('2', '2: Moderate'), ('3', '3: High'), ('4', '4: Expert'), ('5', '5: Almost impossible!')], default='', max_length=1, null=True),
        ),
    ]
