# Generated by Django 3.2.18 on 2023-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('amaryllis', 'Amaryllis'), ('begonia', 'Begonia'), ('bulbs', 'Bulbs'), ('cactus', 'Cactus'), ('chillis', 'Chillis'), ('chinese_money_plant', 'Chinese money plant'), ('dragon_tree', 'Dragon Tree'), ('grape_ivy', 'Grape Ivy'), ('herbs', 'Herbs'), ('hop', 'Hop'), ('kelvin', 'Kelvin'), ('monstera_deliciosa', 'Monstera Deliciosa'), ('oregano_tree', 'Oregano Tree'), ('salads', 'Salads'), ('strawberries', 'Strawberries'), ('suculents', 'Suculents'), ('tomatoes', 'Tomatoes'), ('water_lily', 'Water Lily')], default='normal', max_length=32),
        ),
    ]
