# Generated by Django 3.2.18 on 2023-03-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230305_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_filter',
            new_name='plant_type',
        ),
    ]
