# Generated by Django 3.2.18 on 2023-03-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('specie', models.CharField(choices=[('amaryllis', 'Amaryllis'), ('begonia', 'Begonia'), ('bulbs', 'Bulbs'), ('cactus', 'Cactus'), ('chillis', 'Chillis'), ('chinese_money_plant', 'Chinese money plant'), ('dragon_tree', 'Dragon Tree'), ('grape_ivy', 'Grape Ivy'), ('herbs', 'Herbs'), ('hop', 'Hop'), ('kelvin', 'Kelvin'), ('monstera_deliciosa', 'Monstera Deliciosa'), ('oregano_tree', 'Oregano Tree'), ('salads', 'Salads'), ('strawberries', 'Strawberries'), ('suculents', 'Suculents'), ('tomatoes', 'Tomatoes'), ('water_lily', 'Water Lily'), ('other', 'Other')], max_length=32)),
                ('difficulty_level', models.CharField(choices=[('1', 'Low'), ('2', 'Moderate'), ('3', 'High'), ('4', 'Expert'), ('5', 'Almost impossible!')], default=None, max_length=32)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, default='../default_post_rb5ucj', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
